#
#   spc.py
#   SpaceConfig（.spc）解析器 / Schema 校验 / 序列化
#
#   格式（稳定承诺：2026-09-24 起只做加法，已有 .spc 文件逐字兼容）：
#     # / ; 注释（整行；行尾注释要求 #/; 前有空白，避免误伤 a#b 这类值）
#     [section]           分节
#     key = value         value 支持 "quoted"、true/false、数字、null、[列表]
#   v2 新增（解析侧兼容，旧文件行为不变）：
#     - 引号内转义：\\ \" \' \n \t \r
#     - 行尾注释（引号感知，# 前须有空白）
#     - null / none / ~ / 空值 → None
#     - [elem, elem] 一级列表（元素可 quoted、可嵌套，逗号引号感知）
#   智能侧（纯加法 API）：Schema 声明式校验 + 默认值回填 + 行号定位。
#

from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Tuple
import os
import re

_TRUE = {"true", "yes", "on"}
_FALSE = {"false", "no", "off"}
_NULL = {"null", "none", "nil", "~"}

_ESCAPES = {'\\': '\\', '"': '"', "'": "'", 'n': '\n', 't': '\t', 'r': '\r'}
_ESCAPE_RE = re.compile(r'\\(.)', re.DOTALL)


def _unescape(s: str) -> str:
    def _rep(m):
        ch = m.group(1)
        return _ESCAPES.get(ch, '\\' + ch)  # 未知转义原样保留
    return _ESCAPE_RE.sub(_rep, s)


def _escape(s: str) -> str:
    return (s.replace('\\', '\\\\').replace('"', '\\"')
             .replace('\n', '\\n').replace('\t', '\\t').replace('\r', '\\r'))


def _strip_inline_comment(line: str) -> str:
    """去掉行尾注释：引号感知；#/; 只有在引号外且前面是空白（或行首）时才算注释。"""
    quote = None
    i = 0
    n = len(line)
    while i < n:
        ch = line[i]
        if quote:
            if ch == '\\':
                i += 2
                continue
            if ch == quote:
                quote = None
        elif ch in ('"', "'"):
            quote = ch
        elif ch in ('#', ';') and (i == 0 or line[i - 1] in (' ', '\t')):
            return line[:i]
        i += 1
    return line


def _split_list(inner: str) -> List[str]:
    """顶层逗号切分（引号/括号感知，支持一级嵌套）。"""
    parts, cur, quote, depth = [], '', None, 0
    i = 0
    while i < len(inner):
        ch = inner[i]
        if quote:
            cur += ch
            if ch == '\\' and i + 1 < len(inner):
                cur += inner[i + 1]
                i += 1
            elif ch == quote:
                quote = None
        elif ch in ('"', "'"):
            quote = ch
            cur += ch
        elif ch == '[':
            depth += 1
            cur += ch
        elif ch == ']':
            depth -= 1
            cur += ch
        elif ch == ',' and depth == 0:
            parts.append(cur.strip())
            cur = ''
        else:
            cur += ch
        i += 1
    if cur.strip() or parts:
        parts.append(cur.strip())
    return [p for p in parts if p != '']


def parse_value(raw: str) -> Any:
    """解析单个 value（公开 API，供 spc_set 等复用）。"""
    s = raw.strip()
    if s == '':
        return None
    if len(s) >= 2 and s[0] == s[-1] and s[0] in ('"', "'"):
        return _unescape(s[1:-1])
    if s.startswith('[') and s.endswith(']'):
        return [parse_value(p) for p in _split_list(s[1:-1])]
    low = s.lower()
    if low in _TRUE:
        return True
    if low in _FALSE:
        return False
    if low in _NULL:
        return None
    try:
        return int(s)
    except ValueError:
        pass
    try:
        return float(s)
    except ValueError:
        pass
    return s


# 历史内部名保留（兼容旧 import）
_parse_value = parse_value


def _needs_quote(s: str) -> bool:
    if s == '':
        return True
    return any(c in s for c in ' #;="\'[]\n\t\r')


def format_value(v: Any) -> str:
    """序列化单个 value（公开 API）。"""
    if v is None:
        return 'null'
    if isinstance(v, bool):
        return 'true' if v else 'false'
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, (list, tuple)):
        return '[' + ', '.join(format_value(e) for e in v) + ']'
    s = str(v)
    if _needs_quote(s):
        return '"' + _escape(s) + '"'
    return s


_format_value = format_value


def loads(text: str, with_meta: bool = False):
    """解析 spc 文本。with_meta=True 时返回 (data, meta)，
    meta[(section, key)] = 行号（供 Schema 报错定位）。"""
    data: Dict[str, Dict[str, Any]] = {}
    meta: Dict[Tuple[str, str], int] = {}
    section = 'default'
    data[section] = {}
    for lineno, line in enumerate(text.splitlines(), 1):
        s = _strip_inline_comment(line).strip()
        if not s:
            continue
        if s.startswith('[') and s.endswith(']'):
            section = s[1:-1].strip() or 'default'
            data.setdefault(section, {})
            continue
        if '=' not in s:
            raise SyntaxError(f"spc 第 {lineno} 行缺少 '=': {line!r}")
        k, v = s.split('=', 1)
        k = k.strip()
        data[section][k] = parse_value(v)
        meta[(section, k)] = lineno
    if with_meta:
        return data, meta
    return data


def dumps(data: Dict[str, Dict[str, Any]]) -> str:
    lines = ['# SpaceConfig generated by PySpOS spc.py']
    for section, kv in data.items():
        lines.append(f'[{section}]')
        for k, v in kv.items():
            lines.append(f'{k} = {format_value(v)}')
        lines.append('')
    return '\n'.join(lines).rstrip() + '\n'


def load(path: str, with_meta: bool = False):
    with open(path, 'r', encoding='utf-8') as f:
        return loads(f.read(), with_meta=with_meta)


def dump(data: Dict[str, Dict[str, Any]], path: str) -> None:
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(dumps(data))


def bootcfg_to_spc(bootcfg: dict) -> Dict[str, Dict[str, Any]]:
    return {'boot': {k: v for k, v in bootcfg.items() if k != 'checksum'}}


def spc_to_bootcfg(data: Dict[str, Dict[str, Any]]) -> dict:
    merged: dict = {}
    for section in ('boot', 'default'):
        merged.update(data.get(section, {}))
    return merged


# --------------------------------------------------------------------------
# Schema 校验
# --------------------------------------------------------------------------

@dataclass
class ValidationIssue:
    level: str      # 'error' | 'warning'
    section: str
    key: str
    lineno: int     # 0 表示未知行号
    message: str
    code: str       # MISSING_REQUIRED / TYPE_MISMATCH / NOT_IN_CHOICES /
                    # OUT_OF_RANGE / UNKNOWN_KEY / UNKNOWN_SECTION


class SPCSchemaError(Exception):
    def __init__(self, issues: List[ValidationIssue]):
        self.issues = issues
        super().__init__('; '.join(
            f"[{i.section}.{i.key}@{i.lineno or '?'}] {i.message}"
            for i in issues if i.level == 'error'))


_TYPE_ALIASES = {
    'str': ('str',), 'string': ('str',),
    'int': ('int',), 'integer': ('int',),
    'float': ('float',), 'number': ('int', 'float'),
    'bool': ('bool',), 'boolean': ('bool',),
    'list': ('list',),
    'none': ('none',), 'null': ('none',),
    'any': ('any',),
}


def _type_ok(v: Any, t: str) -> bool:
    t = _TYPE_ALIASES.get(str(t).lower(), ('any',))[0]
    if t == 'any':
        return True
    if t == 'bool':
        return type(v) is bool
    if t == 'int':
        return type(v) is int
    if t == 'float':
        return type(v) in (int, float) and type(v) is not bool
    if t == 'str':
        return isinstance(v, str)
    if t == 'list':
        return isinstance(v, (list, tuple))
    if t == 'none':
        return v is None
    return True


def _type_name(v: Any) -> str:
    if v is None:
        return 'null'
    if type(v) is bool:
        return 'bool'
    if type(v) is int:
        return 'int'
    if type(v) is float:
        return 'float'
    if isinstance(v, str):
        return 'str'
    if isinstance(v, (list, tuple)):
        return 'list'
    return type(v).__name__


def _in_range(v: Any, rule: dict) -> bool:
    lo, hi = rule.get('min'), rule.get('max')
    if lo is None and hi is None:
        return True
    cmp_v = len(v) if isinstance(v, (str, list, tuple)) else v
    if not isinstance(cmp_v, (int, float)):
        return True
    if lo is not None and cmp_v < lo:
        return False
    if hi is not None and cmp_v > hi:
        return False
    return True


def validate(data: Dict[str, Dict[str, Any]], schema: dict,
             meta: Optional[Dict[Tuple[str, str], int]] = None) -> List[ValidationIssue]:
    """按 schema 校验。未知项记 warning（不断链），缺失/类型/越界记 error。

    schema 形如：
      {"boot": {"__allow_unknown__": False,
                "locked": {"type": "bool", "required": True},
                "retries": {"type": "int", "min": 0, "max": 5, "default": 3,
                            "choices": [1, 2, 3], "description": "..."}}}
    顶层 "__allow_unknown__" 控制未知 section（默认 False → warning）。
    """
    meta = meta or {}
    issues: List[ValidationIssue] = []
    sections = {k: v for k, v in schema.items() if not k.startswith('__')}
    top_allow_unknown = bool(schema.get('__allow_unknown__', False))

    def _line(sec, key):
        return meta.get((sec, key), 0)

    for sec, kv in data.items():
        rules = sections.get(sec)
        if rules is None:
            # 空分节多为解析器的人工产物（如恒为空的 default），不打扰用户
            if kv:
                if not top_allow_unknown:
                    issues.append(ValidationIssue(
                        'warning', sec, '', 0,
                        f"未知分节 [{sec}]（schema 未声明，已忽略）", 'UNKNOWN_SECTION'))
            continue
        allow_unknown = bool(rules.get('__allow_unknown__', False))
        key_rules = {k: v for k, v in rules.items() if not k.startswith('__')}
        for key, rule in key_rules.items():
            if rule.get('required') and key not in kv:
                issues.append(ValidationIssue(
                    'error', sec, key, 0,
                    f"缺少必填项 '{key}'"
                    + (f"（{rule.get('description')}）" if rule.get('description') else ''),
                    'MISSING_REQUIRED'))
        for key, v in kv.items():
            rule = key_rules.get(key)
            if rule is None:
                if not allow_unknown:
                    issues.append(ValidationIssue(
                        'warning', sec, key, _line(sec, key),
                        f"未知配置项 '{key}'（schema 未声明，已忽略）", 'UNKNOWN_KEY'))
                continue
            types = rule.get('type', 'any')
            if isinstance(types, str):
                types = [types]
            if not any(_type_ok(v, t) for t in types):
                issues.append(ValidationIssue(
                    'error', sec, key, _line(sec, key),
                    f"'{key}' 类型应为 {'/'.join(types)}，实际为 {_type_name(v)}",
                    'TYPE_MISMATCH'))
                continue
            if 'choices' in rule and v not in rule['choices']:
                issues.append(ValidationIssue(
                    'error', sec, key, _line(sec, key),
                    f"'{key}' 取值 {v!r} 不在允许范围 {rule['choices']} 内",
                    'NOT_IN_CHOICES'))
            elif not _in_range(v, rule):
                issues.append(ValidationIssue(
                    'error', sec, key, _line(sec, key),
                    f"'{key}' 超出范围（min={rule.get('min')} max={rule.get('max')}）",
                    'OUT_OF_RANGE'))
    return issues


def ensure_valid(data, schema, meta=None) -> None:
    """有 error 级问题时抛 SPCSchemaError。"""
    errors = [i for i in validate(data, schema, meta) if i.level == 'error']
    if errors:
        raise SPCSchemaError(errors)


def apply_defaults(data: Dict[str, Dict[str, Any]], schema: dict) -> Dict[str, Dict[str, Any]]:
    """回填 schema 中声明了 default 的缺失项（不修改输入，返回新 dict）。"""
    out = {sec: dict(kv) for sec, kv in data.items()}
    for sec, rules in schema.items():
        if sec.startswith('__') or not isinstance(rules, dict):
            continue
        target = out.setdefault(sec, {})
        for key, rule in rules.items():
            if key.startswith('__') or not isinstance(rule, dict):
                continue
            if key not in target and 'default' in rule:
                target[key] = rule['default']
    return out


# boot 分节预置 schema（供 spc_validate / 迁移工具默认使用）
BOOTCFG_SCHEMA = {
    'boot': {
        'locked': {'type': 'bool', 'required': True, 'description': 'Bootloader 上锁状态'},
        'rootstate': {'type': 'bool', 'required': True, 'description': 'ROOT 持久化状态'},
    }
}
